### ISSUE TITLE
Selection start point never updates

### ISSUE THREAD

**Issue by timLinscott** [acheronfail/VSCodeColumnSelection#1]
This package works fine one time after Sublime is opened. After that, all selections made with shift+alt+click start from the same starting point as the first time the package is used, even if the cursor is placed in a different part of the document. This even holds between panes and windows. If my first selection began three characters into the first document, all future selections will begin three characters into the document.

I'm running Sublime build 3143 on Ubuntu 17.10. The console doesn't report any issues when loading the package at boot.

**Comment by acheronfail** [comment]
Hmm that's very strange indeed. I just tested it on macOS and Debian (both with Sublime 3157) and it seemed to work fine in all cases that you described.

What version of the package do you have installed?
(You can find out by selecting `Package Control: List Packages` from the command palette and finding VSCodeColumnSelection).

In the meantime I'll download 3143 and test on that.

**EDIT:** Okay, it doesn't work in 3143, I'll investigate why.

**Comment by timLinscott** [comment]
v1.0.3. I only just installed it.

**Comment by acheronfail** [comment]
Okay, for some reasons on Sublime 3143 the `sublime_plugin.ViewEventListener.on_text_command` isn't being called (that's where it resets the anchor). I'll see if I can't find anything about that.

EDIT: it seems that `ViewEventListener` only added `on_text_command` in Sublime Text 3155.

**Comment by acheronfail** [comment]
@timLinscott cool, I've found a fix for this, I'll release an update shortly 👍

**Comment by acheronfail** [comment]
@timLinscott thanks for reporting! 👍
